name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release
        cmake --build build
        
    - name: Test
      run: cd build && ctest
